# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_ll_cpp <- function(ances, states, forTime, lambdas, mus, Q, method, atol, rtol, see_states, use_normalization) {
    .Call(`_treeLL_calc_ll_cpp`, ances, states, forTime, lambdas, mus, Q, method, atol, rtol, see_states, use_normalization)
}

